# Generated by Django 4.2.11 on 2025-02-19 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("weblinks", "0002_weblink_shared_with"),
    ]

    operations = [
        migrations.AddField(
            model_name="weblink",
            name="write_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="write_permissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
